const posts = [
  {
    title: "Stock selection with macro factors: the case for simple neural networks",
    date: "January 24, 2026",
    category: "Equity Strategy",
    excerpt:
      "An exploration of how simple neural network architectures can effectively combine macro-quantamental factors for systematic stock selection across global equity markets.",
    slug: "stock-selection-neural-networks",
    readingTime: "12 min read",
    body: `
      <h2>Introduction</h2>
      <p>The intersection of machine learning and macro-quantamental investing offers a promising frontier for systematic equity strategies. In this paper, we investigate whether simple feedforward neural networks can outperform linear models when combining macroeconomic factors for stock selection.</p>
      <p>Traditional factor models rely on linear combinations of signals such as value, momentum, and quality. However, the relationship between macroeconomic states and equity returns is inherently nonlinear. Regime changes, policy shifts, and structural breaks in the global economy all suggest that adaptive, nonlinear models may capture return predictability that linear approaches miss.</p>

      <h2>Data and methodology</h2>
      <p>We use the JPMaQS dataset, which provides point-in-time macroeconomic indicators across 40+ countries. Our feature set includes growth expectations, inflation differentials, external balances, and monetary policy stance indicators, all timestamped to avoid look-ahead bias.</p>
      <p>The neural network architecture is deliberately simple: two hidden layers with ReLU activations, dropout regularization, and batch normalization. We train with a rolling window of 60 months and evaluate out-of-sample over the subsequent 12 months. Cross-validation is performed at the country-sector level to prevent information leakage.</p>

      <h2>Key findings</h2>
      <p>Our results demonstrate that even shallow networks achieve meaningful improvements over linear benchmarks. The long-short portfolio generated by the neural network model produces a Sharpe ratio of 0.72 out-of-sample, compared to 0.48 for the equivalent linear factor model. Importantly, the gains are concentrated during periods of macroeconomic regime change, where nonlinear interactions between factors become most relevant.</p>
      <p>Feature importance analysis reveals that the network learns to weight growth-inflation interactions and policy divergence signals more heavily than a linear model would, suggesting it captures economically meaningful nonlinearities rather than merely overfitting to noise.</p>

      <h2>Implications for portfolio construction</h2>
      <p>These findings suggest that institutional investors using macro-quantamental frameworks for equity selection can benefit from modest increases in model complexity. The key insight is not that deep learning is necessary, but that allowing for nonlinear factor interactions through even a simple network architecture can meaningfully improve risk-adjusted returns.</p>
    `,
  },
  {
    title: "How dollar invoicing and dollar debt shape FX risk premia",
    date: "January 10, 2026",
    category: "Fundamental Value",
    excerpt:
      "The dominance of the US dollar in global trade invoicing and international debt creates systematic risk premia in currency markets that can be captured quantamentally.",
    slug: "dollar-invoicing-fx-risk",
    readingTime: "10 min read",
    body: `
      <h2>The dollar's structural role</h2>
      <p>The US dollar serves as the dominant currency for international trade invoicing and cross-border debt denomination. Approximately 40% of global trade is invoiced in dollars, far exceeding the US share of world trade. Similarly, the majority of international debt securities are denominated in USD. This structural role creates predictable patterns in foreign exchange risk premia.</p>
      <p>Countries with high dollar invoicing shares face amplified exchange rate pass-through to import prices, creating asymmetric adjustment pressures. Meanwhile, those with large dollar-denominated external liabilities face balance sheet vulnerabilities that affect their currency risk profiles.</p>

      <h2>Constructing quantamental indicators</h2>
      <p>Using JPMaQS data, we construct two point-in-time indicators: a dollar invoicing intensity measure and a dollar debt burden measure. Both are calculated relative to country-specific fundamentals and normalized across the cross-section of currencies in our trading universe.</p>
      <p>The invoicing measure captures the share of a country's trade settled in dollars, adjusted for trade openness and bilateral trade patterns with the US. The debt measure captures dollar-denominated external liabilities relative to reserves and export earnings.</p>

      <h2>Trading strategy results</h2>
      <p>A long-short FX strategy that goes long currencies with low dollar vulnerability and short those with high vulnerability generates consistent positive returns. The strategy produces an annualized Sharpe ratio of 0.65 over our 15-year sample period, with particularly strong performance during periods of dollar strength and global risk aversion.</p>
      <p>The factor is largely uncorrelated with traditional carry and momentum strategies, offering genuine diversification benefits for systematic FX portfolios. Drawdowns are contained and recovery periods are shorter than comparable macro factor strategies.</p>

      <h2>Policy implications</h2>
      <p>Our analysis underscores the importance of monitoring dollar dependency metrics in real time. As de-dollarization trends evolve at varying speeds across regions, the cross-sectional dispersion in dollar vulnerability is likely to remain a source of tradable FX risk premia for the foreseeable future.</p>
    `,
  },
  {
    title: "Public finance pressure as a systematic trading factor",
    date: "December 27, 2025",
    category: "Macro Trends",
    excerpt:
      "Government fiscal positions create predictable pressures on sovereign bond markets. We show how to construct a tradable factor from point-in-time public finance data.",
    slug: "public-finance-trading-factor",
    readingTime: "9 min read",
    body: `
      <h2>Fiscal fundamentals and bond markets</h2>
      <p>Sovereign bond yields are influenced by a complex interaction of monetary policy expectations, global risk appetite, and fiscal fundamentals. While the first two factors receive extensive attention, the role of public finance pressure in driving systematic returns has been underexplored in quantitative frameworks.</p>
      <p>We define fiscal pressure as the combination of primary balance deterioration, rising debt service costs, and weakening revenue trends. These indicators, when measured in real time using point-in-time data, provide valuable information about the direction of sovereign spreads.</p>

      <h2>Building the factor</h2>
      <p>Our fiscal pressure composite draws on quarterly fiscal data from the JPMaQS database, covering 30 countries with varying income levels and institutional frameworks. Each component is z-scored within country history and across the cross-section, then combined using equal volatility weighting.</p>
      <p>The critical methodological choice is timing: we use only data that was publicly available at each point in history, accounting for reporting lags and revisions. This avoids the look-ahead bias that plagues much academic research on fiscal fundamentals.</p>

      <h2>Empirical results</h2>
      <p>A long-short sovereign bond strategy based on the fiscal pressure factor generates an information ratio of 0.58 over the full sample. Performance is strongest in emerging markets, where fiscal dynamics are more volatile and less efficiently priced. The factor has low correlation with duration and credit beta, confirming its value as an independent source of return.</p>
      <p>Regime analysis shows the factor performs well in both rising and falling rate environments, suggesting it captures genuine fundamental mispricing rather than a disguised rates bet.</p>

      <h2>Practical considerations</h2>
      <p>Implementation requires careful attention to liquidity constraints, particularly in smaller sovereign markets. We show that restricting the universe to the 20 most liquid sovereign bond markets retains approximately 80% of the theoretical strategy returns while dramatically improving real-world implementability.</p>
    `,
  },
  {
    title: "Alpha through equity-versus-FX trading",
    date: "December 13, 2025",
    category: "Equity Strategy",
    excerpt:
      "Cross-asset relative value strategies that exploit the divergent responses of equity and currency markets to macroeconomic information offer a distinct source of uncorrelated alpha.",
    slug: "alpha-equity-vs-fx",
    readingTime: "11 min read",
    body: `
      <h2>Cross-asset relative value</h2>
      <p>Equity and currency markets respond to macroeconomic news at different speeds and with different sensitivities. Terms-of-trade shocks, for example, tend to be reflected in FX markets within days, while their effect on corporate earnings and equity valuations unfolds over weeks or months. This temporal divergence creates a persistent opportunity for relative value strategies.</p>
      <p>Our approach constructs paired positions: long equity exposure in a country paired with a short position in its currency (or vice versa), based on macroeconomic signals that predict the relative performance of the two asset classes.</p>

      <h2>Signal construction</h2>
      <p>We identify three categories of macro signals that predict equity-FX divergence: real effective exchange rate misalignment, relative growth momentum, and commodity terms-of-trade shifts. Each signal is constructed from point-in-time JPMaQS data and has a clear economic rationale for why it should affect equities and currencies differently.</p>
      <p>The composite signal is formed by equal-weighting the three components after individual normalization. Positions are rebalanced monthly with transaction cost adjustments for both equity and FX legs of each trade.</p>

      <h2>Performance analysis</h2>
      <p>The equity-versus-FX strategy generates a Sharpe ratio of 0.61 after estimated transaction costs, with a maximum drawdown of 8.2% over the 12-year evaluation period. The strategy's returns have near-zero correlation with standalone equity, FX carry, and FX momentum factors, making it a valuable diversifier within a multi-strategy portfolio.</p>
      <p>Country-level decomposition shows that the strongest signals come from commodity-exporting economies, where terms-of-trade dynamics create the largest wedge between equity and currency performance.</p>

      <h2>Conclusion</h2>
      <p>Pairing equity and FX positions based on macro fundamentals offers a structurally differentiated source of alpha. The strategy exploits the inherent speed-of-adjustment differences across asset classes, a feature that is unlikely to be arbitraged away due to institutional segmentation between equity and currency markets.</p>
    `,
  },
  {
    title: "Systematic stock selection with macro factors",
    date: "November 29, 2025",
    category: "Equity Strategy",
    excerpt:
      "A framework for integrating macroeconomic indicators into equity selection models. We demonstrate how point-in-time macro data enhances cross-sectional return forecasts.",
    slug: "systematic-stock-selection-macro",
    readingTime: "14 min read",
    body: `
      <h2>Motivation</h2>
      <p>Conventional equity factor models rely primarily on firm-level data: price momentum, book-to-market ratios, earnings quality, and related metrics. While these factors capture important cross-sectional variation in expected returns, they ignore the macroeconomic context in which firms operate. Two companies with identical firm-level characteristics may have very different expected returns depending on the macro environment of their home country.</p>
      <p>We propose a framework that augments standard equity factors with country-level macroeconomic indicators, using the JPMaQS point-in-time dataset to ensure all information was available to investors at the time of portfolio formation.</p>

      <h2>Framework design</h2>
      <p>Our approach operates in two stages. First, we estimate country-level macro scores using growth expectations, inflation trends, external balance positions, and labor market indicators. Second, we interact these macro scores with firm-level factors to create conditional stock selection signals.</p>
      <p>The key insight is that certain equity factors work better in specific macro regimes. Value stocks tend to outperform when growth expectations are rising from depressed levels, while quality factors dominate during periods of macro deterioration. By conditioning on the macro environment, we can dynamically allocate across factor exposures.</p>

      <h2>Empirical evidence</h2>
      <p>Backtesting across 23 developed and emerging equity markets over a 15-year period, the macro-conditioned model delivers a long-short Sharpe ratio of 0.85, compared to 0.52 for the unconditional factor model. Turnover is moderate, and the improvement is robust to different rebalancing frequencies and transaction cost assumptions.</p>
      <p>Importantly, the macro conditioning reduces the severity of factor drawdowns. The maximum drawdown of the conditional model is 12%, versus 22% for the unconditional benchmark. This improvement arises because the model reduces exposure to factors that are vulnerable in the prevailing macro regime.</p>

      <h2>Implementation notes</h2>
      <p>We discuss practical considerations for implementation, including the treatment of missing macro data, the choice of estimation windows, and the appropriate level of position concentration. The framework is designed to be modular, allowing portfolio managers to incorporate macro conditioning into their existing factor models without a wholesale redesign of their investment process.</p>
    `,
  },
  {
    title: "Macro scorecards for local-currency EM bonds",
    date: "November 8, 2025",
    category: "Fundamental Value",
    excerpt:
      "Composite macro indicators tailored to emerging market sovereign debt help identify value and risk in local-currency bond portfolios across 20+ developing economies.",
    slug: "macro-scorecards-em-bonds",
    readingTime: "10 min read",
    body: `
      <h2>The EM local-currency opportunity</h2>
      <p>Emerging market local-currency sovereign bonds offer attractive yields and diversification benefits, but selecting among 20+ countries requires a disciplined framework. Ad hoc country analysis is resource-intensive and often influenced by recency bias. We propose a systematic scorecard approach that distills the macro outlook for each country into a quantitative composite score.</p>
      <p>The scorecard framework is built on the principle that sovereign bond returns in local currency are driven by three forces: the level and direction of real yields, the trajectory of inflation, and the sustainability of external balances. Each dimension is measured using point-in-time data from the JPMaQS system.</p>

      <h2>Scorecard construction</h2>
      <p>For each country, we compute sub-scores across four dimensions: growth momentum, inflation dynamics, external vulnerability, and policy credibility. Growth momentum captures the direction and acceleration of economic activity. Inflation dynamics measure the gap between realized and expected inflation. External vulnerability assesses current account positions and reserve adequacy. Policy credibility combines central bank track record with fiscal discipline indicators.</p>
      <p>Sub-scores are standardized within each dimension's historical distribution and combined into a single composite using volatility-adjusted weights. The resulting scorecard assigns each country a percentile ranking that updates as new data arrives.</p>

      <h2>Strategy performance</h2>
      <p>A long-short strategy that goes long bonds in the top-scoring countries and short the bottom-scoring countries generates a Sharpe ratio of 0.71 over the evaluation period. The strategy captures approximately 60% of the returns available from perfect foresight, a high information coefficient by the standards of macro factor strategies.</p>
      <p>The scorecard is particularly effective at avoiding distressed credits: countries that eventually experience sovereign stress events consistently rank in the bottom quartile of the scorecard 6-12 months before the event crystallizes.</p>

      <h2>Use in portfolio management</h2>
      <p>Beyond long-short strategies, the scorecard serves as a risk management overlay for benchmark-aware EM bond portfolios. Portfolio managers can use the scores to tilt allocations within tracking error budgets, or to flag positions where the macro outlook has deteriorated significantly relative to spread compensation. The framework's transparency makes it suitable for institutional governance and client reporting.</p>
    `,
  },
];
export { posts };
